package com.alarm.app.model;
// Generated Jun 24, 2019 11:01:53 AM by Hibernate Tools 4.3.5.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * User generated by hbm2java
 */
@Entity
@Table(name = "user", catalog = "dbalarm")
public class User implements java.io.Serializable {

	private String username;
	private String password;
	private Set<Reminder> remindersForMembuatNama = new HashSet<Reminder>(0);
	private Set<Reminder> remindersForMengupdateNama = new HashSet<Reminder>(0);

	public User() {
	}

	public User(String username, String password) {
		this.username = username;
		this.password = password;
	}

	public User(String username, String password, Set<Reminder> remindersForMembuatNama,
			Set<Reminder> remindersForMengupdateNama) {
		this.username = username;
		this.password = password;
		this.remindersForMembuatNama = remindersForMembuatNama;
		this.remindersForMengupdateNama = remindersForMengupdateNama;
	}

	@Id

	@Column(name = "username", unique = true, nullable = false, length = 30)
	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	@Column(name = "password", nullable = false, length = 12)
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "userByMembuatNama")
	public Set<Reminder> getRemindersForMembuatNama() {
		return this.remindersForMembuatNama;
	}

	public void setRemindersForMembuatNama(Set<Reminder> remindersForMembuatNama) {
		this.remindersForMembuatNama = remindersForMembuatNama;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "userByMengupdateNama")
	public Set<Reminder> getRemindersForMengupdateNama() {
		return this.remindersForMengupdateNama;
	}

	public void setRemindersForMengupdateNama(Set<Reminder> remindersForMengupdateNama) {
		this.remindersForMengupdateNama = remindersForMengupdateNama;
	}

}
